services:
  - type: web
    name: vinyl-aggregator-backend
    env: python
    repo: https://github.com/roeigold2002/vinyl-aggregator
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: API_ENV
        value: production
      - key: LOG_LEVEL
        value: info
